version: "3"
services:
  bot:
    image: zhuexe/avrae:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.95"
          memory: 1900M
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
    depends_on:
      - redis
  web:
    image: zhuexe/avraeweb:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ~/data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    networks:
      - webnet
networks:
  webnet: