version: "3"
services:
  bot:
    image: zhuexe/avrae:latest
    volumes:
      - ~/temp:/app/temp
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.8"
          memory: 3500M
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
    depends_on:
      - redis
  web:
    image: zhuexe/avraeweb:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 400M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    depends_on:
      - redis
  redis:
    image: zhuexe/avrae-redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ~/data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    networks:
      - webnet
networks:
  webnet: